custom_dashboard/urls.py
from django.urls import path
from .views import publish

urlpatterns = [
    path("publish/<int:id>/", publish, name="publish"),
]

main/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.views.generic import TemplateView

from wagtail.contrib.sitemaps.views import sitemap
from wagtail.images.views.serve import ServeView
from search import views as search_views
from students.views import StudentLogin, user_logout
from .views import cert, exam_result

urlpatterns = [
    path('django_admin/', admin.site.urls),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("student/login/", StudentLogin.as_view(), name="student_login"),
    path("student/logout/", user_logout, name="student_logout"),
    path("search/", search_views.search, name="search"),
    path("sitemap.xml", sitemap),
    # path('students/', include('students.urls')),
    path("users/", include("users.urls")),
    path("departments/", include("departments.urls")),
    path("batch_records/", include("custom_dashboard.urls")),
    path(
        "service_worker",
        (
            TemplateView.as_view(
                template_name="service_worker.js", content_type="application/javascript"
            )
        ),
        name="service_worker",
    ),
    # path('manifest', (
    #     TemplateView.as_view(
    #         template_name="manifest.json",
    #         content_type='application/json')), name='manifest'),
    re_path(
        r"^images/([^/]*)/(\d*)/([^/]*)/[^/]*$",
        ServeView.as_view(),
        name="wagtailimages_serve",
    ),
    path('cert', cert, name="cert"),
    path("exam_result/<int:id>/", exam_result, name="exam_result"),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

custom_dashboard/models.py
from django.db import models
from django.core.validators import ValidationError
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
from django.utils.formats import localize
from django.utils.translation import gettext_lazy as _
from django import forms

from modelcluster.models import ClusterableModel

from wagtail.core.models import Orderable, Collection
from wagtail.documents import get_document_model
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, ObjectList
from modelcluster.fields import ParentalKey

from wagtail.admin.edit_handlers import (
    FieldPanel,
)
from wagtail.core.fields import RichTextField
from django.contrib.auth import get_user_model
from students.models import StudentRecord
from departments.models import BatchYear, YEARS
from main.decorators import disable_for_loaddata
from datetime import datetime
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

User = get_user_model()
channel_layer = get_channel_layer()

status_choice = (("pending", "Pending"), ("decline", "Decline"), ("approve", "Approve"), ("processing", "Processing"), ("invalid", "Invalid"))
year_choice = [(2022,2022), (2023,2023)]
semester_choice = ((1, "I"), (2, "II"),)
level_choices = [(1,1), (2,2), (3,3), (4,4)]

def data_default():
    return {
        "is_lock": False,
        "prev_status": None,
        "comments": "",
        "document": {},
        "is_publish": False,
    }


class RecordsManager(models.Manager):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .select_related(
                "institute", "assigned_controller", "assigned_pr", "link_document"
            )
        )



class StudentRecords(ClusterableModel, Orderable, models.Model):
    institute = ParentalKey(
        "institutes.Institute",
        null=True,
        blank=False,
        related_name="institute_student_records",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    assigned_controller = models.ForeignKey(
        "users.CustomUser",
        limit_choices_to={"role__name": "Controller of Exam"},
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_controller",
        verbose_name="Controller of Exam",
    )
    assigned_pr = models.ForeignKey(
        "users.CustomUser",
        limit_choices_to={"role__name": "Proof Reader of Exam"},
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="assigned_proof_reader",
        verbose_name="Proof Reader of Exam",
    )
    link_document = models.OneToOneField(
        "institutes.CustomDocument",
        null=True,
        blank=True,
        related_name="+",
        on_delete=models.CASCADE,
    )
    term = models.IntegerField(
        choices=semester_choice, default=1
    )
    level = models.IntegerField(
        choices=level_choices, default=1
    )
    exam_held = models.IntegerField(null=True, blank=False, choices=YEARS.choices)
    year = models.IntegerField(null=True, blank=False, choices=YEARS.choices)
    batches = models.ManyToManyField(
        "departments.BatchYear",
        related_name="student_record_year_batch",
        verbose_name="Batches",
    )
    updated_by = models.ForeignKey(
        "users.CustomUser",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="updated_by",
        verbose_name="Updated by",
    )

    active = models.BooleanField(default=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    comment = RichTextField(null=True, blank=True)
    approve_at = models.DateTimeField(null=True)
    
    status = models.CharField(choices=status_choice, default="processing", max_length=50)
    data = models.JSONField(default=data_default)
    
    timestamp = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False)
    objects = RecordsManager()

    class Meta:
        verbose_name = "Student Batch Record"
        verbose_name_plural = "Student Batch Records"
        unique_together = ["institute", "year", "term", "level"]

    def delete(self, force=False):
        BatchUploadResult.objects.filter(batch_file=self).delete()
        self.link_document.delete()
        super(StudentRecords, self).delete()


    def clean(self, *args, **kwargs):
        print(f"StudentRecords ID={self.id}")
        print(self.assigned_controller)
        if not self.name:
            self.name = str(self.link_document)
            self.data["is_lock"] = True
            
        if self.status == "approve":
            self.approve_at = datetime.now()
        
        if self.data.get('prev_status') == "invalid" and self.link_document.file_hash == self.link_document.prev_hash:
            raise ValidationError("Batch file didn't change.")

        if (
            self.assigned_controller
            and not self.assigned_controller.role.name == "Controller of Exam"
        ):
            raise ValidationError("Assign role should be a Controller of Exam.")

        if (
            self.assigned_pr
            and not self.assigned_pr.role.name == "Proof Reader of Exam"
        ):
            raise ValidationError("Assign role should be a Proof Reader of Exam.")
        
        if self.status == "decline" and not self.comment:
            raise ValidationError("Please add a comment.")


        lock = ['approve', 'processing']
        if self.status in lock:
            self.data["is_lock"] = True
            
        else:
            self.data["is_lock"] = False

        self.data["prev_status"] = self.status

    def __str__(self):
        return f"Batch Record - Level-{self.level} Term-{self.term} {self.year} Held-{self.exam_held}"

    def get_record_count(self):
        return str(StudentRecord.objects.filter(record=self).count())

    def extract_timeout(self):
        if self.status == "processing":
            n = datetime.now() - self.timestamp
            if 600 < n.total_seconds():
                return True
        return False

        

certs = (('Provisional', 'Provisional'),)
def batch_data():
    return {
        "certificate_issued":[],
    }
class BatchUploadResult(ClusterableModel, Orderable, models.Model):
    batch_file = ParentalKey(
        StudentRecords,
        null=True,
        blank=False,
        related_name="institute_student_records",
        on_delete=models.SET_NULL,
    )
    students = models.ManyToManyField(
        'users.CustomUser', related_name="batch_upload_result", blank=True, limit_choices_to={"role__name": "Student"},
    )
    collection = models.OneToOneField(Collection,on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+")
    batch_year = models.ForeignKey(
        "departments.BatchYear",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="+",
    )
    certificates = models.CharField(choices=certs, max_length=50, default="Provisional")
    date = models.CharField(null=True, blank=False, max_length=120)
    data = models.JSONField(default=batch_data)

    class Meta:
        verbose_name = "Certificate"
        verbose_name_plural = "Certificate Generator"
        unique_together = ["batch_file", "batch_year"]
    def __str__(self):
        return str(self.batch_year)

    edit_handler = ObjectList([
        FieldPanel('certificates'),
        FieldPanel('date'),
        FieldPanel('students',  widget=forms.CheckboxSelectMultiple),
    ])

@receiver(post_save, sender=BatchUploadResult)
def record_post_save(sender, instance, *args, **kwargs):
    from wagtail.admin.forms.collections import CollectionForm

    
    parent = instance.batch_year.collection
    if parent and not instance.collection:
        name = f'{parent.name} - Files'
        existing_collection = Collection.objects.filter(name=name).first()
        if not existing_collection:
            form = CollectionForm({'parent':parent.pk, 'name':name})
            
            if form.is_valid():
                collection = form.save(commit=False)
                parent.add_child(instance=collection)
                collection.save()
                instance.collection = collection
                instance.save()
        elif existing_collection and not instance.collection:
            instance.collection = existing_collection
            instance.save()

@receiver(post_save, sender=StudentRecords)
def record_post_save(sender, instance, created, *args, **kwargs):
    Document = get_document_model()
    doc = Document.objects.filter(id=instance.link_document.id).first()
    f_data = doc.get_data()

    if doc.prev_hash != doc.file_hash:
        doc.has_task = True

    if instance.id:
        f_data['student_records_id'] = instance.id


    if created:
        print("StudentRecords CREATED")
        doc.has_task = True
        # f_data['student_records_id'] = instance.id

        # doc.department = instance.batch_year.batch.department
        # doc.collection = instance.batch_year.collection
        # doc.batch = instance.batch_year
        # instance.status = 'pending'
        # instance.save(update_fields=["status"])
        
        
    else:
        
        if instance.data.get("is_publish") != instance.publish:
            print("publish state change")
            
            records = StudentRecord.objects.filter(record=instance).update(
                publish=instance.publish
            )
            print(f"updated {records}")

            instance.data["is_publish"] = instance.publish
            # instance.save(update_fields=["data"])
            StudentRecords.objects.filter(id=instance.id).update(data=instance.data)
            batch_result = BatchUploadResult.objects.filter(batch_file=instance)
            if instance.publish and not batch_result:

custom_dashboard/views.py
from django.shortcuts import HttpResponseRedirect
from django.utils.translation import gettext_lazy as _
from wagtail.admin import messages
from .models import StudentRecords


def publish(request, id):
    print("publishing")
    print(id)
    sr = StudentRecords.objects.get(id=id)
    if not request.user.is_superuser and str(request.user.role) != "Controller of Exam":
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    if (
        str(request.user.role) == "Controller of Exam"
        and sr.assigned_controller != request.user
    ):
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

    print(sr)
    if sr.publish:
        sr.publish = False
        sr.save()

        messages.success(
            request,
            _("{0}' Unpublish.").format(sr),
        )
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    else:
        sr.publish = True
        sr.save()

        messages.success(
            request,
            _("{0}' Publish.").format(sr),
        )
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

custom_dashboard/templates/modeladmin/student_records/create.html
{% extends "custombase.html" %}
{% load i18n wagtailadmin_tags modeladmin_tags %}

{% block titletag %}{{ view.get_meta_title }}{% endblock %}

{% block extra_css %}
    {{ block.super }}

    {{ media.css }}
{% endblock %}

{% block extra_js %}
    {{ block.super }}

    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ media.js }}

    {% prepopulated_slugs %}

    <script>
        $(function() {
            $('[data-wagtail-tooltip]').tooltip({
                animation: false,
                title: function() {
                    return $(this).attr('data-wagtail-tooltip');
                },
                trigger: 'hover',
                placement: 'bottom',
            });
        })
        $(document).ready(function(){
            $("#createTab").attr('aria-selected', true);
        })
    </script>
{% endblock %}



    {% block header %}
        {% include "wagtailadmin/shared/header_with_locale_selector.html" with title=view.get_page_title subtitle=view.get_page_subtitle icon=view.header_icon merged=1 %}
    {% endblock %}
    {% block content_main %}
    <form id="baseForm" action="{% block form_action %}{{ view.create_url }}{% endblock %}{% if locale %}?locale={{ locale.language_code }}{% endif %}"{% if is_multipart %} enctype="multipart/form-data"{% endif %} class="nice-padding" method="POST" novalidate>
        {% csrf_token %}

        {% block form %}{{ edit_handler.render_form_content }}{% endblock %}

        {% block footer %}
            <footer class="footer">
                <ul>
                    <li class="actions footer__container">
                        {% block form_actions %}
                            <div class="dropdown dropup dropdown-button match-width">
                                <button type="submit" class="button action-save button-longrunning" data-clicked-text="{% trans 'Saving…' %}">
                                    {% icon name="spinner" %}<em>{% trans 'Save' %}</em>
                                </button>
                            </div>
                        {% endblock %}
                    </li>
                </ul>
            </footer>
        {% endblock %}
    </form>
    {% endblock %}

custom_dashboard/templates/modeladmin/student_records/edit.html
{% extends "modeladmin/student_records/create.html" %}
{% load i18n wagtailadmin_tags %}

{% block header %}
    {% include "modeladmin/includes/header_with_history.html" with title=view.get_page_title subtitle=view.get_page_subtitle icon=view.header_icon merged=1 latest_log_entry=latest_log_entry history_url=history_url %}
    
    <script>
        $(document).ready(function(){
            {% if request.user.role.name == 'Proof Reader of Exam' %}
            let chooserActions = $("#id_link_document-chooser").find('li');
            chooserActions.remove()
            {% endif %}
            let commentSection = $("#commentSection");
            $("li.char_field").prepend(commentSection)
            commentSection.show();
            {% if request.user.role.name == "Controller of Exam" %}
            $("#createTab").text('Edit');
            {% endif %}
        })
    </script>
    <section id="commentSection" style="display:none;">
        {{ instance.data.comments|safe }}
    </section>
    {% include "modeladmin/student_records/include/table_.html" with dt=dt %}
{% endblock %}

{% block form_action %}{{ view.edit_url }}{% endblock %}

{% block form_actions %}

    <div class="dropdown dropup dropdown-button match-width">
        <button type="submit" class="button action-save button-longrunning" data-clicked-text="{% trans 'Updating..' %}">
            {% icon name="spinner" %}<em>{% trans 'Update' %}</em>
        </button>

        {% if user_can_delete %}
            <div class="dropdown-toggle">{% icon name="arrow-up" %}</div>
            <ul>
                <li><a href="{{ view.delete_url }}" class="shortcut">{% trans "Delete" %}</a></li>
            </ul>
        {% endif %}

    </div>
{% endblock %}

custom_dashboard/templates/modeladmin/student_records/index.html
{% extends "custombase.html" %}
{% load i18n modeladmin_tags wagtailadmin_tags %}

{% block bodyclass %}modeladmin{% endblock %}

{% block titletag %}{{ view.get_meta_title }}{% endblock %}

{% block css %}
    {{ block.super }}
    {{ view.media.css }}
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {{ view.media.js }}
{% endblock %}


    {% block header %}
        <header class="w-header w-header--hasform">
            {% block breadcrumb %}{% endblock %}
            <div class="row">
                <div class="left header-left">
                    <div class="col">
                        {% block h1 %}
                            <h1 class="w-header__title">
                                {% if view.header_icon %}{% icon class_name="w-header__glpyh" name=view.header_icon %}{% endif %}
                                {{ view.get_page_title }}
                                {% if view.get_page_subtitle %} <span class="w-header__subtitle">{{ view.get_page_subtitle }}</span> {% endif %}
                                {% include 'modeladmin/includes/result_count.html' %}
                            </h1>
                        {% endblock %}
                    </div>
                    {% block search %}{% search_form %}{% endblock %}
                </div>
                {% block header_extra %}
                    <div class="right header-right">
                        
                    </div>
                {% endblock %}
            </div>
            {% block extra_rows %}{% endblock %}
        </header>
    {% endblock %}

    {% block content_main %}
        
        
   
        <div class="main-content">
            <div class="row">
                {% block content_cols %}

                    {% comment %} {% block filters %}
                        {% if view.has_filters and all_count %}
                            <div class="changelist-filter col3">
                                <h2>{% trans 'Filter' %}</h2>
                                {% for spec in view.filter_specs %}{% admin_list_filter view spec %}{% endfor %}
                            </div>
                        {% endif %}
                    {% endblock %} {% endcomment %}

                    <div class="result-list col12">
                        {% block result_list %}
                            {% if not all_count %}
                                <div class="nice-padding" style="margin-top:30px;">
                                    {% if no_valid_parents %}
                                        <p>{% blocktrans trimmed with view.verbose_name_plural as name %}No {{ name }} have been created yet. One of the following must be created before you can add any {{ name }}:{% endblocktrans %}</p>
                                        <ul>
                                            {% for type in required_parent_types %}<li><b>{{ type|title }}</b></li>{% endfor %}
                                        </ul>
                                    {% else %}
                                        <p>{% blocktrans trimmed with view.verbose_name_plural as name %}No {{ name }} have been created yet.{% endblocktrans %}
                                            {% if user_can_create %}
                                                {% blocktrans trimmed with view.create_url as url %}
                                                    <a href="{{ url }}">Upload now</a>?
                                                {% endblocktrans %}
                                            {% endif %}</p>
                                    {% endif %}
                                </div>
                            {% else %}
                                {% result_list %}
                            {% endif %}
                        {% endblock %}
                    </div>

                    {% block pagination %}
                        <nav class="pagination col12" aria-label="{% trans 'Pagination' %}">
                            <p>{% blocktrans trimmed with page_obj.number as current_page and paginator.num_pages as num_pages %}Page {{ current_page }} of {{ num_pages }}.{% endblocktrans %}</p>
                            {% if paginator.num_pages > 1 %}
                                <ul>
                                    {% pagination_link_previous page_obj view %}
                                    {% pagination_link_next page_obj view %}
                                </ul>
                            {% endif %}
                        </nav>
                    {% endblock %}

                {% endblock %}
            </div>
        </div>
        
   
    {% endblock %}