main/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.views.generic import TemplateView

from wagtail.contrib.sitemaps.views import sitemap
from wagtail.images.views.serve import ServeView
from search import views as search_views
from students.views import StudentLogin, user_logout
from .views import cert, exam_result

urlpatterns = [
    path('django_admin/', admin.site.urls),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("student/login/", StudentLogin.as_view(), name="student_login"),
    path("student/logout/", user_logout, name="student_logout"),
    path("search/", search_views.search, name="search"),
    path("sitemap.xml", sitemap),
    # path('students/', include('students.urls')),
    path("users/", include("users.urls")),
    path("departments/", include("departments.urls")),
    path("batch_records/", include("custom_dashboard.urls")),
    path(
        "service_worker",
        (
            TemplateView.as_view(
                template_name="service_worker.js", content_type="application/javascript"
            )
        ),
        name="service_worker",
    ),
    # path('manifest', (
    #     TemplateView.as_view(
    #         template_name="manifest.json",
    #         content_type='application/json')), name='manifest'),
    re_path(
        r"^images/([^/]*)/(\d*)/([^/]*)/[^/]*$",
        ServeView.as_view(),
        name="wagtailimages_serve",
    ),
    path('cert', cert, name="cert"),
    path("exam_result/<int:id>/", exam_result, name="exam_result"),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

users/urls.py
from django.urls import path
from .views import get_listing, department_list, get_student_listing
from .wagtail_views import edit, index, create
app_name = "users"
urlpatterns = [
    path("list", get_listing, name="get_listing"),
    path("list/student", get_student_listing, name="get_student_listing"),
    path("department/list", department_list, name="department_list"),
    # path("", index, name="index"),
    # path("add/", create, name="add"),
    # path("<str:user_id>/", edit, name="edit"),
    
    # re_path(r'^create/$', post_create, name='post_create'),
    # re_path(r'^(?P<id>\d+)/edit_post/$', post_update, name='post_update'),
    # re_path(r'^(?P<id>\d+)/delete_post/$', post_delete, name='post_delete'),
    # re_path(r'^(\d+)/toggle/$', toggle_comment, name='toggle_comment'),
    # re_path(r'^(\d+)/deletecomment/$', delete_comment, name='delete_comment'),
    # re_path(r'^(?P<id>\d+)/edit_featuredpost/$', featuredpost_update, name='featuredpost_update'),
    # url(r'^captcha/', include('captcha.urls')),
]

users/models.py
from django.db import models
from django.contrib.auth.models import *
from django.core.validators import RegexValidator
from django.db.models.signals import post_save

from django.contrib.auth.models import Group

from departments.models import *
from students.models import StudentRecord
from django.conf import settings


class CustomGroup(models.Model):
    role = models.ForeignKey(
        Group,
        verbose_name="Role",
        related_name="group_role",
        blank=True,
        null=True,
        on_delete=models.DO_NOTHING,
    )
    roles = models.ManyToManyField(
        Group, verbose_name="Role", related_name="custom_group", blank=True
    )

    class Meta:
        verbose_name = "Group"
        verbose_name_plural = "Groups"


def meta_default():
    return {
        "batch": {},
        "prev_role": None,
        "formated_id": None,
        "student_records": {},
    }


class MyAccountManager(BaseUserManager):
    def get_queryset(self):
        if str(self.model.role) == "Student":
            return (
                super()
                .get_queryset()
                .select_related("institute", "department", "batch")
            )

        return super().get_queryset().select_related("institute", "department", "role")

    def create_user(self, email, username, password=None):
        print("create_user is called!")
        if not email:
            raise ValueError("Users must have an email address.")
        if not username:
            raise ValueError("Users must have a username.")

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user


class CustomUser(AbstractUser):
    institute = models.ForeignKey(
        "institutes.Institute", on_delete=models.SET_NULL, null=True, blank=False
    )
    department = models.ForeignKey(
        "departments.Department", on_delete=models.SET_NULL, null=True, blank=False
    )

    id_suffix_validator = RegexValidator(regex=r"^[0-9]+$", message="Numbers only")
    suffix = models.CharField(
        validators=[id_suffix_validator], max_length=3, null=True, blank=False
    )
    role = models.ForeignKey(
        Group,
        verbose_name="Role",
        related_name="user_role",
        blank=False,
        null=True,
        on_delete=models.DO_NOTHING,
    )
    metadata = models.JSONField(default=meta_default, null=True, blank=True)

    batch = models.ForeignKey(
        "departments.Batch",
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="students_batch",
    )
    degree = models.ForeignKey(
        "institutes.Degree",
        on_delete=models.SET_NULL,
        null=True,
        blank=False,
        related_name="student_degree",
    )
    # objects = MyAccountManager()
    prev_role = None

    def clean(self, *args, **kwargs):
        super(CustomUser, self).clean(*args, **kwargs)
        if self.batch and not str(self.role) == "Student":
            self.role = Group.objects.get(name="Student")
            # self.groups.set([self.role])
            self.department = self.batch.department
            self.institute = self.department.institute
            self.degree = self.batch.degree
        

            
        print("DONE")

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"
        
    def get_publish_record(self):
        print("get_publish_record")
        if self.metadata.get("student_records") and len(
            self.metadata.get("student_records")
        ):

            records = self.metadata.get("student_records")
            print("records")
            print(records.keys())
            for k, v in records.items():
                print(v.keys())
                print(v.get("publish"))
                if v.get("publish"):
                    return v.get("data")

        return False

    def get_student_names_by_dept(institute_id, sheet_name):
        print('get_student_names_by_dept')
        print(f'SHEET NAME {sheet_name}')
        print(institute_id)
        
        qset = CustomUser.objects.filter(institute__id=institute_id, batch__name=sheet_name, role__name="Student")
        name_list = list(qset.values_list("username", flat=True))
        # qset = list(qset)
        print(qset)
        print(f'name_list {name_list}')
        return name_list, qset

    def get_subjects_header(self):
        record = StudentRecord.objects.filter(student=self, publish=True).last()
        if record:
            source = record.data
            if source:
                subjects = source.get("Subjects")

                print(subjects)
                data = {
                    "total_credits_completed_in_this_term": "",
                    "total_credits_taken_in_this_term": "",
                    "failed_subject": "",
                    "result": "",
                    "term_gpa": "",
                    "cgpa": "",
                }
                for k, item in source.items():
                    print(f"source {k}")
                    print(f"val {item}")
                    if not k == "Subjects":
                        f = k.lower().replace("  ", "_").replace(" ", "_")
                        if f.startswith("total_credits_taken_in_this_term"):
                            data["total_credits_taken_in_this_term"] = item
                        if f.startswith("total_credits_completed_in_this_term"):
                            data["total_credits_completed_in_this_term"] = item
                        if f.startswith("failed_subject"):
                            data["failed_subject"] = item
                        if f.startswith("result"):
                            data["result"] = item
                        if f.startswith("cgpa"):
                            data["cgpa"] = item
                        if f.endswith("gi_of_the_term"):
                            data["term_gpa"] = item

                print(data)
                return data
        return False

    def get_grade_results(self):
        records = StudentRecord.objects.filter(student=self, publish=True).order_by('record__level', 'record__term')
        print(f"RECORDS \n{records}")
        return records

    def get_publish_results(self):
        records = StudentRecord.objects.filter(student=self, publish=True, retake=False).order_by('record__level', 'record__term')
        
        print(f"RECORDS \n{records}")
        return records
        
    def set_last_seen(self, d):
        self.metadata['last_seen'] = d
        self.save()

class OnlineUsers(models.Model):

	# all users who are authenticated and viewing the chat
	title 				= models.CharField(max_length=255, unique=True, blank=False,)
	users 				= models.JSONField(null=True, blank=True, default=dict())

	def __str__(self):
		return self.title

	def connect_user(user):
		"""
		return true if user is added to the users list
		"""
		if not str(user.role) == 'Student':
			user_id = user.id

			self = OnlineUsers.objects.first()
			connected = False
			print("connect_USER!")
			print(user_id)
			print(self)
			print(self.users)
			print(self.users.get(str(user_id)))

			if not self.users.get(str(user_id)):
				connected = True
				user.set_last_seen('Online')
				
			self.users[str(user_id)] = {
										'connected': True,
									}
			self.save()
			
			print("___________________END")
			return connected 

	def disconnect_user(user_id):
		"""
		return true if user is removed from the users list
		"""
		self = OnlineUsers.objects.first()

		is_user_removed = False
		if self.users.get(str(user_id)):
			self.users[str(user_id)] = {
										'connected': False,
									}
			self.save()

			is_user_removed = True

		return is_user_removed
	
	def is_user_connected(user):
		self = OnlineUsers.objects.first()

		connected = False
		if self.users.get(str(user.id)):
			if self.users[str(user.id)]['connected']:
				connected = True
			else:
				self.users.pop(str(user.id), None)
				self.save()
				d = str(datetime.now())
				user.set_last_seen(d)

		connected_users = len(OnlineUsers.get())
		return connected, connected_users

	def get():
		self = OnlineUsers.objects.first()
		data = []
		if self:
			for k,v in self.users.items():
				data.append(int(k))
				
		return data


instance = OnlineUsers.objects.first()
if not instance:
    OnlineUsers.objects.create(title='All online users')

def post_save_receiver(sender, instance, created, **kwargs):
    pass


post_save.connect(post_save_receiver, sender=settings.AUTH_USER_MODEL)

users/views.py
from django.http import JsonResponse
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required

from institutes.models import Institute
from departments.models import Department, Batch, BatchYear
from .models import CustomGroup

# Create your views here.
@login_required
def get_listing(request):
    data = []
    data2 = []

    if request.user.is_superuser:
        group_qset = Group.objects.all()
        institute_qset = Institute.objects.all()
    else:
        custom_group = CustomGroup.objects.filter(role=request.user.role).first()
        group_qset = custom_group.roles.all().exclude(name="Super User").exclude(name="Student")
        institute_qset = Institute.objects.filter(id=request.user.institute.id)

    for item in group_qset:
        custom_id = item.id
        if item.id <= 9:
            custom_id = f"0{item.id}"

        data.append(
            {
                "id": item.id,
                "name": item.name,
                "custom_id": custom_id,
            }
        )

    for item in institute_qset:
        data2.append({"id": item.id, "name": item.name, "custom_id": item.code})

    return JsonResponse({"status": 200, "roles": data, "institutes": data2}, safe=False)


@login_required
def get_student_listing(request):
    data = []
    data2 = []
    data3 = []
    if (
        request.method == "POST"
        and request.user.is_superuser
        or str(request.user.role) == "Faculty Member"
    ):
        institute_id = request.POST.get("institute_id")
        department_id = request.POST.get("department_id")

        if request.user.is_superuser:
            if department_id:
                batch_qset = BatchYear.objects.filter(batch__department__id=int(department_id))

                for i in batch_qset:
                    if i.batch.degree.id <= 9:
                        custom_id = f"0{i.batch.degree.id}"
                    data2.append(
                        {
                            "year": i.year,
                            "degree_id": custom_id,
                            "id": i.batch.id,
                            "name": i.batch.name+" "+i.batch.suffix,
                        }
                    )

            else:
                inst_qset = Institute.objects.all()
                for i in inst_qset:
                    data3.append({"id": i.id, "code": i.code, "name": i.name})

                if institute_id:
                    dept_qset = Department.objects.filter(
                        institute__id=int(institute_id)
                    )
                    for i in dept_qset:
                        data.append(
                            {"id": i.id, "custom_id": i.custom_id, "name": i.name}
                        )

        if str(request.user.role) == "Faculty Member":
            data3.append(
                {
                    "id": request.user.institute.id,
                    "code": request.user.institute.code,
                    "name": request.user.institute.name,
                }
            )
            data.append(
                {
                    "id": request.user.department.id,
                    "custom_id": request.user.department.code,
                    "name": request.user.department.name,
                }
            )

            for i in Batch.objects.filter(assigned_faculty_member=request.user):
                if i.degree.id <= 9:
                    custom_id = f"0{i.degree.id}"
                    data2.append(
                        {
                            "year": i.year,
                            "degree_id": custom_id,
                            "id": i.id,
                            "name": i.name+" "+i.suffix,
                        }
                    )

        return JsonResponse(
            {"status": 200, "institutes": data3, "departments": data, "batches": data2},
            safe=False,
        )


@login_required
def department_list(request):
    id = request.GET.get("id")

    departments = Department.objects.filter(institute__id=id)

    if departments:
        data = []
        for item in departments:
            data.append({"id": item.id, "name": item.name, "custom_id": item.custom_id})
        return JsonResponse({"status": 200, "departments": data}, safe=False)

users/templates/fragments/js/custom_group.html
<script>
    window.addEventListener('load', (event) => {
        let userCheckbox = $( "legend:contains('Permissions')" ).closest("fieldset").find("tr:contains('User')").find('input');
        let up1 = $(userCheckbox[0]);
        let up2 = $(userCheckbox[1]);
        let up3 = $(userCheckbox[2]);
    
        toggleField()
        userCheckbox.change(function(){
            console.log("change")
            toggleField()
        })

        function toggleField(){
            if(up1.is(":checked") || up2.is(":checked") || up3.is(":checked")){
                $("div[data-contentpath='custom_group']").show();
            }else{
                $("#id_custom_group").val("");
                $("div[data-contentpath='custom_group']").hide();
            }
        }
    })
</script>

users/templates/fragments/js/user_role_listing.html
<script>
    $(document).ready(function(){
        let groupSelect = $("#id_role");
        let departmentSelect = $("#id_department");
        let instituteSelect = $("#id_institute");
        let init = true;
        let currentGroup = groupSelect.val();
        let currentInstitute = instituteSelect.val();
        groupSelect.empty();
        {% if request.user.is_superuser %}
        instituteSelect.empty();
        {% endif %}
        $.ajax({
                type: 'GET',
                dataType: "json",
                url: "{% url 'users:get_listing' %}",
                cache:false,
                success:function(res){
                    console.log(res)
                    if(res.status === 200){
                        
                        $.each(res.roles, function(k,v){
                            groupSelect.append("<option value='"+v.id+"' custom-id='"+v.custom_id+"'>"+v.name+"</option> ")
                        })
                        {% if request.user.is_superuser %}
                        $.each(res.institutes, function(k,v){
                            instituteSelect.append("<option value='"+v.id+"' custom-id='"+v.custom_id+"'>"+v.name+"</option> ")
                        })
                        {% endif %}
    
                    }
                }
        }).done(function(){
            instituteSelect.trigger('change');
            if(init){
                init = false;
                groupSelect.val(currentGroup);
                instituteSelect.val(currentInstitute);
            }
        })
    
    
        instituteSelect.on('change', function(){
            console.log($(this).val())
            departmentSelect.empty();
    
            $.ajax({
                type: 'GET',
                dataType: "json",
                url: "{% url 'users:department_list' %}",
                data:{id:$(this).val()},
                cache:false,
                success:function(res){
                    console.log(res)
                    if(res.status === 200){
                        
                        $.each(res.departments, function(k,v){
                            console.log(v)
                            departmentSelect.append("<option value='"+v.id+"' custom-id='"+v.custom_id+"'>"+v.name+"</option> ")
                        })
    
                    }
                }
            }).done(function(){
                updateID();
            })
    
        });
    
        departmentSelect.on('change', function(){
            updateID();
        });
    
        groupSelect.on('change', function(){
            updateID();
            option = $(this).find('option[value='+$(this).val()+']').text();
            if (option === 'Institute Head' || option === 'Controller of Exam' || option === 'Proof Reader of Exam'){
                $('div[data-contentpath="department"]').hide()
                departmentSelect.val('')
            }else{
                $('div[data-contentpath="department"]').show()
            }
        });
    
        $("#id_suffix").on('change', function(){
            updateID();
        });
    
        let userID;
        function updateID(){
           
            instituteId = instituteSelect.val();
            if(!instituteId){
                instituteId=''
            }
            if(instituteId <= 9){
                instituteId = "0"+instituteId;
            }
            departmentId = departmentSelect.val();
            if(!departmentId){
                departmentId=''
            }
            if(departmentId <= 9){
                departmentId = "0"+departmentId;
            }
            groupId = groupSelect.val();
            if(!groupId){
                groupId=''
            }
            if(groupId <= 9){
                groupId = "0"+groupId;
            }
    
            userID = instituteId + '-' + departmentId + '-' + groupId;
            if($("#id_suffix").val().length){
                userID = userID + '-' + $("#id_suffix").val();
            }
    
            $("#id_username").val(userID.replaceAll('-',''));
        }
    
    
    })
    </script>
    